import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { registerUser, createProfile } from "./reduxAPI";
import { pushErrorNotification } from "../../Error/reduxSlice";
import { setUserAvl } from "../../User/reduxSlice";
import { loginUser, rememberAfterLogin } from "../Login/reduxAPI";

// icon
import { Icon } from "@iconify/react";

const initialState = {
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  confirmPassword: "",
  rememberMe: true,
  loading: false,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(createUserAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

export const registerUserAsync = createAsyncThunk(
  "register/createUser",
  async (
    { email, password, navigate, firstName, lastName },
    { dispatch, getState, rejectWithValue }
  ) => {
    try {
      // create user
      const userCredential = await registerUser(email, password);

      // assigning attendee role
      await createProfile(firstName, lastName, email, password);

      // Relogin

      // const userCredentialLogin = await loginUser(email, password);
      // const user = userCredentialLogin.user;
      // if (user) {
      //   dispatch(setUserAvl({ userAvl: true }));
      // }

      // const { data } = await rememberAfterLogin(
      //   userCredentialLogin.user.uid,
      //   rememberMe
      // );
 
      // localStorage.setItem("preEventToken", data.token);

      navigate("/", { replace: true });
    } catch (error) {
      if (error.name === "FirebaseError") {
        dispatch(
          pushErrorNotification({
            notify: {
              iconifyIconLink: (
                <Icon icon="bx:notification" className="rounded" />
              ),
              errorTitle: error.code,
              errorMessage: error.message,
              theme: "danger",
              time: "now",
              autoHideTime: 3000,
              statusCode: 200,
              show: true,
            },
          })
        );
      }
      return rejectWithValue(error);
    }
  }
);

export const registerSlice = createSlice({
  name: "register",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setFirstName: (state, action) => {
      state.firstName = action.payload.firstName;
    },
    setLastName: (state, action) => {
      state.lastName = action.payload.lastName;
    },

    setEmail: (state, action) => {
      state.email = action.payload.email;
    },
    setPassword: (state, action) => {
      state.password = action.payload.password;
    },
    setConfirmPassword: (state, action) => {
      state.confirmPassword = action.payload.confirmPassword;
    },
    toggleRememberMe: (state, action) => {
      state.rememberMe = !state.rememberMe;
    },

    clearRegisterInputs: (state, action) => {
      state.role = "attendee";
      state.firstName = "";
      state.lastName = "";
      state.email = "";
      state.password = "";
      state.confirmPassword = "";
      state.rememberMe = true;
      state.loading = false;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(registerUserAsync.pending, (state, action) => {
        state.loading = true;
      })
      .addCase(registerUserAsync.fulfilled, (state, action) => {
        state.loading = false;
      })
      .addCase(registerUserAsync.rejected, (state, action) => {
        state.loading = false;
      });
  },
});

export const {
  setEmail,
  setPassword,
  setFirstName,
  setLastName,
  setConfirmPassword,
  toggleRememberMe,

  clearRegisterInputs,
} = registerSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const loginState = (state) => state.register;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
export const incrementIfOdd = (amount) => (dispatch, getState) => {
  const currentValue = loginState(getState());
  if (currentValue % 2 === 1) {
    // dispatch(incrementByAmount(amount));
  }
};

export default registerSlice.reducer;
